// src/lib/components/EmptyState.svelte
<script lang="ts">
  import * as Card from '$lib/components/ui/card/index.js';

  let { title, description }: { title: string; description: string } = $props();
</script>

<Card.Root class="shadow-none">
  <Card.Content class="space-y-2 p-6 text-center">
    <h3 class="text-lg font-semibold">{title}</h3>
    <p class="mx-auto max-w-md text-sm leading-6 text-muted-foreground">{description}</p>
  </Card.Content>
</Card.Root>

// src/components/empty-state.tsx
import { Card, CardContent } from "@/components/ui/card";

export function EmptyState({
  title,
  description
}: {
  title: string;
  description: string;
}) {
  return (
    <Card className="shadow-none">
      <CardContent className="space-y-2 p-6 text-center">
        <h3 className="text-lg font-semibold">{title}</h3>
        <p className="mx-auto max-w-md text-sm leading-6 text-muted-foreground">{description}</p>
      </CardContent>
    </Card>
  );
}
