// src/lib/components/MonthInput.svelte
<script lang="ts">
  import { Input } from '$lib/components/ui/input/index.js';
  import { Label } from '$lib/components/ui/label/index.js';

  let {
    id,
    label,
    value = $bindable(1),
    helper,
    onValueChange
  }: {
    id: string;
    label: string;
    value: number;
    helper?: string;
    onValueChange?: (value: number) => void;
  } = $props();

  function handleInput(event: Event) {
    const next = Number((event.currentTarget as HTMLInputElement).value);
    value = Number.isFinite(next) ? next : 1;
    onValueChange?.(value);
  }
</script>

<div class="space-y-2">
  <Label for={id}>{label}</Label>
  <Input
    {id}
    min={1}
    step={1}
    type="number"
    value={Number.isFinite(value) ? value : 1}
    oninput={handleInput}
  />
  {#if helper}
    <p class="text-xs leading-5 text-muted-foreground">{helper}</p>
  {/if}
</div>

// src/components/month-input.tsx
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

export function MonthInput({
  id,
  label,
  value,
  onChange,
  helper
}: {
  id: string;
  label: string;
  value: number;
  onChange: (value: number) => void;
  helper?: string;
}) {
  return (
    <div className="space-y-2">
      <Label htmlFor={id}>{label}</Label>
      <Input
        id={id}
        min={1}
        step={1}
        type="number"
        value={Number.isFinite(value) ? value : 1}
        onChange={(event) => onChange(Number(event.target.value))}
      />
      {helper ? <p className="text-xs leading-5 text-muted-foreground">{helper}</p> : null}
    </div>
  );
}
