// src/components/section-card.tsx
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

export function SectionCard({
  title,
  description,
  children,
  actions
}: {
  title: string;
  description?: string;
  children: React.ReactNode;
  actions?: React.ReactNode;
}) {
  return (
    <Card className="shadow-none">
      <CardHeader className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
        <div className="space-y-1.5">
          <CardTitle>{title}</CardTitle>
          {description ? <CardDescription>{description}</CardDescription> : null}
        </div>
        {actions ? <div className="flex items-center gap-2">{actions}</div> : null}
      </CardHeader>
      <CardContent>{children}</CardContent>
    </Card>
  );
}

// src/lib/components/SectionCard.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import * as Card from '$lib/components/ui/card/index.js';

  let {
    title,
    description,
    children,
    actions
  }: {
    title: string;
    description?: string;
    children: Snippet;
    actions?: Snippet;
  } = $props();
</script>

<Card.Root class="shadow-none">
  <Card.Header class="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
    <div class="space-y-1.5">
      <Card.Title>{title}</Card.Title>
      {#if description}
        <Card.Description>{description}</Card.Description>
      {/if}
    </div>
    {#if actions}
      <div class="flex items-center gap-2">{@render actions()}</div>
    {/if}
  </Card.Header>
  <Card.Content>
    {@render children()}
  </Card.Content>
</Card.Root>
